version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8080
      DB_NAME: 'TaskManager'
      DB_USER: 'myuser'
      DB_PASSWORD: 'mypassword'
      DB_HOST: 'db'  # Use the service name of the database
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: TaskManager
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data

volumes:
  my_db_data:

